language: cpp

dist: trusty
sudo: required

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

before_install:
  - if [[ "$TRAVIS_OS_NAME" == linux ]]; then sudo apt-get update -qq                   ; fi
  - if [[ "$TRAVIS_OS_NAME" == linux ]]; then sudo apt-get install -y libboost-all-dev  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update                               ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew outdated boost || brew upgrade boost ; fi

script:
  - mkdir build
  - cd build
  - cmake .. && make